version: '3.8'

services:
        web:
                build: ./services/web
                command: python manage.py run -h 0.0.0.0
                volumes:
                        - ./services/web:/usr/src/app
                ports:
                        - "5000:5000"
                env_file:
                        - ./.env.dev
        db:
                image: postgres:13-alpine
                hostname: postgres
                volumes:
                        - postgres_data:/var/lib/postgresql/data
                environment:
                        - POSTGRES_USER=flask
                        - POSTGRES_PASSWORD=flask
                        - POSTGRES_DB=dev
        pgadmin:
                image: dpage/pgadmin4
                restart: unless-stopped
                volumes:
                        - pgadmin:/var/lib/pgadmin
                environment:
                        PGADMIN_DEFAULT_EMAIL: dev@concordia.ca
                        PGADMIN_DEFAULT_PASSWORD: root
                ports:
                        - "5050:80"

volumes:
        postgres_data:
        pgadmin:
